---
os: Linux
dist: focal
git:
  depth: 250
language: ruby
bundler_args: --jobs 4 --retry 2 --without packaging documentation
before_install:
  - gem update --system --force
script: "bundle exec rake $CHECK"
notifications:
  email: false

jobs:
  include:
    - stage: pxp-agent lint
      rvm: 2.5
      env: "CHECK=rubocop"
    - stage: pxp-agent lint
      rvm: 2.5
      env: "CHECK=commits"
